package mandatoryHomeWork;/*
* You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.
*
* Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
*
*
* Pseudocode:
* 1. In the for loop () add the asci values of tSum + sumAscii sSum
* 2. Get the last character Ascii value
* 3. tSum - sSum -- print the corresponding ascii
*
* */

import org.testng.annotations.Test;

public class DiffStrings {

    @Test
    public void test1(){
        String t = "abcde";
        String s = "abcd";
        findTheDifference(s,t);
    }
    @Test
    public void test2(){
        String s = "cat";
        String t = "atbc";

        findTheDifference(s,t);
    }
    @Test
    public void test3(){
        String t = "c";
        String s = "";
        findTheDifference(s,t);
    }
    public char findTheDifference(String s, String t) {

        int tSum = 0;
        int sSum = 0;

        for(int i=0;i<s.length();i++){

            tSum = tSum+t.charAt(i);
            sSum = sSum+s.charAt(i);

        }
        tSum = tSum+t.charAt(t.length()-1);
        char ch = (char)(tSum-sSum);

        return ch;
    }


}
